#!/bin/bash
echo 'sudo apt-get -y install git' >> .bash_profile
echo 'git config --global user.name "j-tyler"' >> .bash_profile
echo 'git config --global user.email "justin.marsh@holbertonschool.com"' >> .bash_profile
echo 'function parse_git_dirty {' >> .bash_profile
echo '  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working directory clean" ]] && echo "*"' >> .bash_profile
echo '}' >> .bash_profile
echo 'function parse_git_branch {' >> .bash_profile
echo '  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"' >> .bash_profile
echo '}' >> .bash_profile
echo 'export PS1="\[\033[1;30m\]\u \[\033[0;37m\]@\h \[\033[1;32m\]\w\[\033[0m\]\n\[\033[1;31m\]\$(parse_git_branch) \[\033[0m\]\$ "' >> .bash_profile
