#!/bin/bash
sudo apt-get -y install git
echo 'git config --global user.name "Larry Madeo"' >> .bash_profile
echo 'git config --global user.email "lmadeo76@gmail.com"' >> .bash_profile
git clone https://github.com/holbertonschool/Betty.git
echo 'mkdir -p ~/.vim/colors' >> .bash_profile
echo 'curl -o ~/.vim/colors/desertEx.vim https://raw.githubusercontent.com/flazz/vim-colorschemes/master/colors/desertEx.vim' >> .bash_profile
echo 'function parse_git_dirty {' >> .bash_profile
echo '  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working directory clean" ]] && echo "*"' >> .bash_profile
echo '}' >> .bash_profile
echo 'function parse_git_branch {' >> .bash_profile
echo '  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"' >> .bash_profile
echo '}' >> .bash_profile
echo 'export PS1="\[\033[1;30m\]\u \[\033[0;37m\] \[\033[1;32m\]\w\[\033[0m\]\n\[\033[1;31m\]\$(parse_git_branch) \[\033[0m\]\$ "' >> .bash_profile
echo 'betty() {' >> .bash_profile
echo '        ~/Betty/betty-style.pl $1' >> .bash_profile
echo '        ~/Betty/betty-doc.pl $1' >> .bash_profile
echo '}' >> .bash_profile
echo 'tabstospaces() {' >> .bash_profile
echo 'find . -name "*.$1" ! -type d -exec bash -c 'ex -c ":%s/\t/    /g" -c ":wq" "$0"' {} \;' >> .bash_profile
echo '}' >> .bash_profile
echo 'colorscheme desertEx' >> .vimrc
echo 'set tabstop=4 shiftwidth=4' >> .vimrc
